name: .NET Unit Tests (Develop)

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-test-unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.36

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Unit Tests
      run: dotnet test ./Homies.UnitTests/Homies.UnitTests.csproj --no-build --verbosity normal

